### PR TITLE
reviews

### PR DESCRIPTION
**Pull request by vanya-n23**
tommow il did it

### CODE REVIEW

**Review by DarkLordSith — CHANGES_REQUESTED** [review]
Please provide changes:
- connect your js to main.js
- fix style for back button (inactive)

**Comment by vanya-n23** [comment]
f

**Comment by vanya-n23** [comment]
did

**Review by DarkLordSith — CHANGES_REQUESTED** [review]
Please provide correct connection for js to main.js - has the problem

**Comment by vanya-n23** [comment]
try again i tryed to fix

**Review by DarkLordSith — APPROVED** [review]

**Pull request merged**
