### PR TITLE
add style for tablet and desc

### PR DESCRIPTION
**Pull request by BohdanKret**

### CODE REVIEW

**Review by DarkLordSith — CHANGES_REQUESTED** [review]
pull main update
recheck code
fix conflict

**Comment by BohdanKret** [comment]
Success merge you can approve 
fixet conflict

**Review by DarkLordSith — CHANGES_REQUESTED** [review]
Background dots to png format

**Comment by BohdanKret** [comment]
add all changes
add all styles from design layout to form.css

**Review by DarkLordSith — APPROVED** [review]

**Pull request merged**
